"""create account table

Revision ID: 47f3a4aed281
Revises:
Create Date: 2021-05-09 17:44:59.997848

"""
from alembic import op
import sqlalchemy as sa
import model


# revision identifiers, used by Alembic.
revision = "47f3a4aed281"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema my_schema")
    op.create_table(
        "user",
        sa.Column("id", model.ULIDType(length=26), nullable=False),
        sa.Column("fullname", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="my_schema",
    )
    op.create_table(
        "email",
        sa.Column("id", model.ULIDType(length=26), nullable=False),
        sa.Column("user_id", model.ULIDType(length=26), nullable=True),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["my_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="my_schema",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email", schema="my_schema")
    op.drop_table("user", schema="my_schema")
    # ### end Alembic commands ###
