"""Added User table

Revision ID: 867e7740574b
Revises:
Create Date: 2021-05-08 11:18:47.498558

"""
from alembic import op
import sqlalchemy as sa
import model


# revision identifiers, used by Alembic.
revision = "867e7740574b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'my_schema' ) EXEC('CREATE SCHEMA [my_schema]')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", model.ULIDType(length=26), nullable=False),
        sa.Column("fullname", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="my_schema",
    )
    op.create_table(
        "email",
        sa.Column("id", model.ULIDType(length=26), nullable=False),
        sa.Column("user_id", model.ULIDType(length=26), nullable=True),
        sa.Column("email_address", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["my_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="my_schema",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email", schema="my_schema")
    op.drop_table("user", schema="my_schema")
    # ### end Alembic commands ###
    op.execute("drop schema [my_schema]")
